/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_allocator;

import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author S. A. SULEIMAN
 */
public class LendersPage extends javax.swing.JFrame {

    /**
     * Creates new form LendersPage
     */
    public LendersPage() {
        initComponents();
        setResourceModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("library_manager?characterEncoding=utf8PU").createEntityManager();
        resourcesQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Resources r");
        resourcesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : resourcesQuery.getResultList();
        resourcesQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Resources r");
        resourcesList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : resourcesQuery1.getResultList();
        resourcesQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Resources r");
        resourcesList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : resourcesQuery2.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        mat_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        submitLendersBtn = new javax.swing.JButton();
        foundMsg = new javax.swing.JLabel();
        lendDate = new com.toedter.calendar.JDateChooser();
        retrunDate = new com.toedter.calendar.JDateChooser();
        bookTitle = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        r_id = new javax.swing.JLabel();
        r_copies = new javax.swing.JLabel();
        r_type = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        registerLink = new javax.swing.JMenu();
        userLink_item = new javax.swing.JMenuItem();
        resourceLink_item = new javax.swing.JMenuItem();
        ledersLink = new javax.swing.JMenu();
        lendResourceLink_item = new javax.swing.JMenuItem();
        lendHistoryLink_item = new javax.swing.JMenuItem();
        historyLink = new javax.swing.JMenu();
        registeredUsersLink_item = new javax.swing.JMenuItem();
        resourcesLink_item = new javax.swing.JMenuItem();
        helpLink = new javax.swing.JMenu();
        documentationlink_item = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        logoutLink_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("lend a resource");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Team Bob Lee (C) 2018");

        mat_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mat_idKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Date Collected:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Returning Date:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("User Id:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Resource Title:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Resource ID:");

        submitLendersBtn.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        submitLendersBtn.setText("Submit");
        submitLendersBtn.setEnabled(false);
        submitLendersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitLendersBtnActionPerformed(evt);
            }
        });

        foundMsg.setFont(new java.awt.Font("Tw Cen MT", 3, 14)); // NOI18N

        bookTitle.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bookTitleItemStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Resource Type:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Available copies:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        r_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r_id.setText("_");

        r_copies.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r_copies.setText("_");

        r_type.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r_type.setText("_");

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        registerLink.setText("Register");
        registerLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLinkActionPerformed(evt);
            }
        });

        userLink_item.setText("User");
        userLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(userLink_item);

        resourceLink_item.setText("Resource");
        resourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(resourceLink_item);

        jMenuBar1.add(registerLink);

        ledersLink.setText("Lend");
        ledersLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lendResourceLink_item.setText("Lend resource");
        lendResourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendResourceLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendResourceLink_item);

        lendHistoryLink_item.setText("Lending history");
        lendHistoryLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendHistoryLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendHistoryLink_item);

        jMenuBar1.add(ledersLink);

        historyLink.setText("View");
        historyLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        registeredUsersLink_item.setText("Registered Users");
        registeredUsersLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredUsersLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(registeredUsersLink_item);

        resourcesLink_item.setText("Resources");
        resourcesLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(resourcesLink_item);

        jMenuBar1.add(historyLink);

        helpLink.setText("Help");
        helpLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        documentationlink_item.setText("About");
        helpLink.add(documentationlink_item);

        jMenuItem8.setText("Documentation");
        helpLink.add(jMenuItem8);

        jMenuBar1.add(helpLink);

        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        logoutLink_item.setText("Logout");
        logoutLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLink_itemActionPerformed(evt);
            }
        });
        logout.add(logoutLink_item);

        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(217, 217, 217))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(29, 29, 29))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addComponent(jLabel14)))
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(39, 39, 39)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mat_id)
                                    .addComponent(foundMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(r_id)
                                    .addComponent(r_copies)
                                    .addComponent(r_type)
                                    .addComponent(lendDate, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(retrunDate, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(476, 476, 476)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(229, 229, 229)
                                .addComponent(submitLendersBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addComponent(jLabel1)
                    .addContainerGap(232, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(mat_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(foundMsg)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12))
                    .addComponent(bookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(r_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(r_copies)
                        .addGap(18, 18, 18)
                        .addComponent(r_type))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lendDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(retrunDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(submitLendersBtn)
                .addGap(256, 256, 256)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(49, 49, 49))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel1)
                    .addContainerGap(739, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitLendersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitLendersBtnActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String lendedDate, returningDate;
        lendedDate = sdf.format(lendDate.getDate());
        returningDate = sdf.format(retrunDate.getDate());
        
        LendersController lendersController = new LendersController(
                mat_id.getText(),
                String.valueOf(bookTitle.getSelectedItem()),
                lendedDate, 
                returningDate
        );
        
        if (lendersController.validateInput()){
            try{
                lendersController.connectToDB();
                lendersController.registerLender();
                JOptionPane.showMessageDialog(null, "Resource lended Successfully", "OKAY..!!", JOptionPane.INFORMATION_MESSAGE);
                clearInputs(); 
                // System.out.print(confirmResponse);                
                
            }catch(Exception e){
                clearInputs();
                submitLendersBtn.setEnabled(false);
                JOptionPane.showMessageDialog(null, "An Error has occured \n Technical errror details: " + e.toString(), "error msg", JOptionPane.ERROR_MESSAGE);
            }
        
        }else{
            JOptionPane.showMessageDialog(null, "Resource not lended \n check date entered", "Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitLendersBtnActionPerformed

    private void mat_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mat_idKeyReleased
        //JOptionPane.showMessageDialog(null, mat_id.getText());
       try{
            LendersController lendersController = new LendersController(mat_id.getText());
            lendersController.connectToDB();
            
            if(lendersController.checkMatric_Id(mat_id.getText())){
               // JOptionPane.showMessageDialog(null, "SUCCESS "+ mat_id.getText() + " does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
               submitLendersBtn.setEnabled(true); 
               foundMsg.setText(null);
            }else{
                submitLendersBtn.setEnabled(false);
                foundMsg.setForeground(Color.red);
                   foundMsg.setText("Matric/Id not found");
            }
            //JOptionPane.showMessageDialog(null, "SUCCESS "+ mat_id.getText() + " does not exist", "ERROR", JOptionPane.ERROR_MESSAGE);
            
       }catch(SQLException e){
           JOptionPane.showMessageDialog(null, e, "ERROR", JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_mat_idKeyReleased

    private void userLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLink_itemActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLink_itemActionPerformed

    private void resourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceLink_itemActionPerformed
        // TODO add your handling code here:
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourceLink_itemActionPerformed

    private void registerLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLinkActionPerformed

    }//GEN-LAST:event_registerLinkActionPerformed

    private void lendResourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendResourceLink_itemActionPerformed
        new LendersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendResourceLink_itemActionPerformed

    private void lendHistoryLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendHistoryLink_itemActionPerformed
        new LendersView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendHistoryLink_itemActionPerformed

    private void registeredUsersLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredUsersLink_itemActionPerformed
        new UsersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registeredUsersLink_itemActionPerformed

    private void resourcesLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesLink_itemActionPerformed
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourcesLink_itemActionPerformed

    private void logoutLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLink_itemActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLink_itemActionPerformed

    private void bookTitleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bookTitleItemStateChanged
        //System.out.println(bookTitle.getSelectedItem());
        LendersController lendersController = new LendersController();
        try {
            
            lendersController.getResourceDetails(bookTitle.getSelectedItem().toString());
            r_id.setText(lendersController.resourceId);
            r_copies.setText(lendersController.resourceCopies);
            r_type.setText(lendersController.resourceType);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex, "Error", JOptionPane.ERROR_MESSAGE);
//            Logger.getLogger(LendersPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bookTitleItemStateChanged

    public void clearInputs(){
        bookTitle.setSelectedIndex(0);//.setSelectedItem(null);
        mat_id.setText(null);
        lendDate.setDate(null);
        retrunDate.setDate(null);
        this.dispose();
        new LendersPage().main(null);
        
    }
    
    public void setResourceModel(){
        
		try (
                        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/library_manager", "root", "");
                        Statement st = connect.createStatement();) {
			Class.forName("com.mysql.jdbc.Driver");
			String sql = "SELECT title FROM resources WHERE availability = 1 AND copies > 0";
			ResultSet rs = st.executeQuery(sql);
			ResultSetMetaData metaData = rs.getMetaData();
			int columns = metaData.getColumnCount();
                       
                        while (rs.next()) {
                            
                                for (int i = 1; i <= columns; i++) {
                                      bookTitle.addItem(rs.getObject(i).toString());
				}
                                
			}
		} catch (Exception e) {
			System.out.println(e);
		}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LendersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LendersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LendersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LendersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LendersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookTitle;
    private javax.swing.JMenuItem documentationlink_item;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel foundMsg;
    private javax.swing.JMenu helpLink;
    private javax.swing.JMenu historyLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu ledersLink;
    private com.toedter.calendar.JDateChooser lendDate;
    private javax.swing.JMenuItem lendHistoryLink_item;
    private javax.swing.JMenuItem lendResourceLink_item;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem logoutLink_item;
    private javax.swing.JTextField mat_id;
    private javax.swing.JLabel r_copies;
    private javax.swing.JLabel r_id;
    private javax.swing.JLabel r_type;
    private javax.swing.JMenu registerLink;
    private javax.swing.JMenuItem registeredUsersLink_item;
    private javax.swing.JMenuItem resourceLink_item;
    private javax.swing.JMenuItem resourcesLink_item;
    private java.util.List<library_allocator.Resources> resourcesList;
    private java.util.List<library_allocator.Resources> resourcesList1;
    private java.util.List<library_allocator.Resources> resourcesList2;
    private javax.persistence.Query resourcesQuery;
    private javax.persistence.Query resourcesQuery1;
    private javax.persistence.Query resourcesQuery2;
    private com.toedter.calendar.JDateChooser retrunDate;
    private javax.swing.JButton submitLendersBtn;
    private javax.swing.JMenuItem userLink_item;
    // End of variables declaration//GEN-END:variables

 
    
}