/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_allocator;

import java.awt.TextArea;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class LendersView extends javax.swing.JFrame {

    /**
     * Creates new form LendersView
     */
    public LendersView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("library_manager?characterEncoding=utf8PU").createEntityManager();
        lendedQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM Lended l");
        lendedList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lendedQuery.getResultList();
        lendedQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT l FROM Lended l");
        lendedList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : lendedQuery1.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        lendersTable = new javax.swing.JTable();
        sendNotificationBtn = new javax.swing.JButton();
        returnedBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        registerLink = new javax.swing.JMenu();
        userLink_item = new javax.swing.JMenuItem();
        resourceLink_item = new javax.swing.JMenuItem();
        ledersLink = new javax.swing.JMenu();
        lendResourceLink_item = new javax.swing.JMenuItem();
        lendHistoryLink_item = new javax.swing.JMenuItem();
        historyLink = new javax.swing.JMenu();
        registeredUsersLink_item = new javax.swing.JMenuItem();
        resourcesLink_item = new javax.swing.JMenuItem();
        helpLink = new javax.swing.JMenu();
        documentationlink_item = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        logoutLink_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("lenders");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Team Bob Lee (C) 2018");

        lendersTable.setAutoCreateRowSorter(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lendedList1, lendersTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${matricOrId}"));
        columnBinding.setColumnName("Matric Or Id");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${bookTitle}"));
        columnBinding.setColumnName("Book Title");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dateCollected}"));
        columnBinding.setColumnName("Date Collected");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${returnDate}"));
        columnBinding.setColumnName("Return Date");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${status}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(lendersTable);

        sendNotificationBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        sendNotificationBtn.setText("Send Notification");
        sendNotificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendNotificationBtnActionPerformed(evt);
            }
        });

        returnedBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        returnedBtn.setText("Returned");
        returnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnedBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        registerLink.setText("Register");
        registerLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLinkActionPerformed(evt);
            }
        });

        userLink_item.setText("User");
        userLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(userLink_item);

        resourceLink_item.setText("Resource");
        resourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(resourceLink_item);

        jMenuBar1.add(registerLink);

        ledersLink.setText("Lend");
        ledersLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lendResourceLink_item.setText("Lend resource");
        lendResourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendResourceLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendResourceLink_item);

        lendHistoryLink_item.setText("Lending history");
        lendHistoryLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendHistoryLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendHistoryLink_item);

        jMenuBar1.add(ledersLink);

        historyLink.setText("View");
        historyLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        registeredUsersLink_item.setText("Registered Users");
        registeredUsersLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredUsersLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(registeredUsersLink_item);

        resourcesLink_item.setText("Resources");
        resourcesLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(resourcesLink_item);

        jMenuBar1.add(historyLink);

        helpLink.setText("Help");
        helpLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        documentationlink_item.setText("About");
        helpLink.add(documentationlink_item);

        jMenuItem8.setText("Documentation");
        helpLink.add(jMenuItem8);

        jMenuBar1.add(helpLink);

        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        logoutLink_item.setText("Logout");
        logoutLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLink_itemActionPerformed(evt);
            }
        });
        logout.add(logoutLink_item);

        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(228, 228, 228))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(returnedBtn)
                        .addGap(69, 69, 69)
                        .addComponent(sendNotificationBtn)
                        .addGap(0, 408, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendNotificationBtn)
                    .addComponent(returnedBtn))
                .addGap(74, 74, 74)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendNotificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendNotificationBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = lendersTable.getSelectedRow();
        
        if(selectedRowIndex >= 0 ){
            Object status = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 5);
            Object bookTitle = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 2);
            Object dateCollected = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 3);
            Object returnDate = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 4);
            Object userMatric_Id = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 1);
            
            if((Boolean)status == false){
            
                try{
                    LendersController lendersController = new LendersController(userMatric_Id.toString());
                    lendersController.connectToDB();
                    String phoneNumber =  lendersController.getLenderPhone(userMatric_Id.toString());
                   
                    String smsBody = "Hello,\nPlease be reminded that you are to return a resource you lended from the library\nwith title: " 
                        + bookTitle + "\non " + dateCollected;
                    
                    JTextArea tx = new javax.swing.JTextArea();
                    tx.setColumns(20);
                    tx.setRows(5);
                    tx.setText(smsBody);
                    
                    JFrame frame = new JFrame();
                    String[] options = new String[2];
                    options[0] = "Send SMS";
                    options[1] = "Cancel";
                    
                 int i =   JOptionPane.showOptionDialog(frame.getContentPane(),tx, "Phone Number: " + phoneNumber, 0,JOptionPane.INFORMATION_MESSAGE,null,options,null);
                 
                 if(i == 0){
                     
                     try{
                         HttpURLCon http = new HttpURLCon(phoneNumber, tx.getText());
                         //System.out.println("Sending HTTP GET request");
                         http.sendGet();
                     }catch(Exception e){
                         JOptionPane.showMessageDialog(null, e, "Error sending SmS", JOptionPane.ERROR_MESSAGE);
                     }
                     
                 }
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e, "An error has occured", JOptionPane.ERROR_MESSAGE);
                }
                
            }

        }
//        System.out.println(selectedRowIndex);
//        Object matric_id = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 4);
        
    }//GEN-LAST:event_sendNotificationBtnActionPerformed

    private void returnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnedBtnActionPerformed
        // When user has returned book
        int selectedRowIndex = lendersTable.getSelectedRow();
        
        if(selectedRowIndex >= 0 ){
            Object status = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 5);
            Object id = (Object) lendersTable.getModel().getValueAt(selectedRowIndex, 0);

            if((Boolean)status == false){
             
             int confirmAction =  JOptionPane.showConfirmDialog(null, "Are you sure user has returned resource?", "Confirm action", JOptionPane.YES_NO_OPTION);
             
             if(confirmAction == 0){
                try{
                   LendersController lendersController = new LendersController(id.toString());
                   lendersController.connectToDB();
                   lendersController.updateLenderStatus(id.toString());
                   JOptionPane.showMessageDialog(null, "Operation SUCCESSFULLY.", "success", JOptionPane.PLAIN_MESSAGE);
                   
                   this.dispose();
                   new LendersView().main(null);
                   
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e, "An error has occured", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            
            }

        }
                
    }//GEN-LAST:event_returnedBtnActionPerformed

    private void userLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLink_itemActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLink_itemActionPerformed

    private void resourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceLink_itemActionPerformed
        // TODO add your handling code here:
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourceLink_itemActionPerformed

    private void registerLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLinkActionPerformed

    }//GEN-LAST:event_registerLinkActionPerformed

    private void lendResourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendResourceLink_itemActionPerformed
        new LendersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendResourceLink_itemActionPerformed

    private void lendHistoryLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendHistoryLink_itemActionPerformed
        new LendersView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendHistoryLink_itemActionPerformed

    private void registeredUsersLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredUsersLink_itemActionPerformed
        new UsersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registeredUsersLink_itemActionPerformed

    private void resourcesLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesLink_itemActionPerformed
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourcesLink_itemActionPerformed

    private void logoutLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLink_itemActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLink_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LendersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LendersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LendersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LendersView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LendersView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem documentationlink_item;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JMenu helpLink;
    private javax.swing.JMenu historyLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu ledersLink;
    private javax.swing.JMenuItem lendHistoryLink_item;
    private javax.swing.JMenuItem lendResourceLink_item;
    private java.util.List<library_allocator.Lended> lendedList;
    private java.util.List<library_allocator.Lended> lendedList1;
    private javax.persistence.Query lendedQuery;
    private javax.persistence.Query lendedQuery1;
    private javax.swing.JTable lendersTable;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem logoutLink_item;
    private javax.swing.JMenu registerLink;
    private javax.swing.JMenuItem registeredUsersLink_item;
    private javax.swing.JMenuItem resourceLink_item;
    private javax.swing.JMenuItem resourcesLink_item;
    private javax.swing.JButton returnedBtn;
    private javax.swing.JButton sendNotificationBtn;
    private javax.swing.JMenuItem userLink_item;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
