/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_allocator;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tasiu Kwaplong Saeed
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dept = new javax.swing.JTextField();
        mat_id = new javax.swing.JTextField();
        fullName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        registerUserBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        registerLink = new javax.swing.JMenu();
        userLink_item = new javax.swing.JMenuItem();
        resourceLink_item = new javax.swing.JMenuItem();
        ledersLink = new javax.swing.JMenu();
        lendResourceLink_item = new javax.swing.JMenuItem();
        lendHistoryLink_item = new javax.swing.JMenuItem();
        historyLink = new javax.swing.JMenu();
        registeredUsersLink_item = new javax.swing.JMenuItem();
        resourcesLink_item = new javax.swing.JMenuItem();
        helpLink = new javax.swing.JMenu();
        documentationlink_item = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        logoutLink_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Page");
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("register new user");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Team Bob Lee (C) 2018");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Unique Id:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Full Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Phone Number:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Category:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Department:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Residential Address:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Email:");

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Staff" }));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        registerUserBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerUserBtn.setText("Register");
        registerUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUserBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        registerLink.setText("Register");
        registerLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLinkActionPerformed(evt);
            }
        });

        userLink_item.setText("User");
        userLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(userLink_item);

        resourceLink_item.setText("Resource");
        resourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(resourceLink_item);

        jMenuBar1.add(registerLink);

        ledersLink.setText("Lend");
        ledersLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lendResourceLink_item.setText("Lend resource");
        lendResourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendResourceLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendResourceLink_item);

        lendHistoryLink_item.setText("Lending history");
        lendHistoryLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendHistoryLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendHistoryLink_item);

        jMenuBar1.add(ledersLink);

        historyLink.setText("View");
        historyLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        registeredUsersLink_item.setText("Registered Users");
        registeredUsersLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredUsersLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(registeredUsersLink_item);

        resourcesLink_item.setText("Resources");
        resourcesLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(resourcesLink_item);

        jMenuBar1.add(historyLink);

        helpLink.setText("Help");
        helpLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        documentationlink_item.setText("About");
        helpLink.add(documentationlink_item);

        jMenuItem8.setText("Documentation");
        helpLink.add(jMenuItem8);

        jMenuBar1.add(helpLink);

        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        logoutLink_item.setText("Logout");
        logoutLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLink_itemActionPerformed(evt);
            }
        });
        logout.add(logoutLink_item);

        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(229, 229, 229))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel15))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(dept)
                                                    .addComponent(mat_id)
                                                    .addComponent(fullName)
                                                    .addComponent(category, 0, 302, Short.MAX_VALUE))
                                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(registerUserBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(mat_id, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(fullName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(registerUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUserBtnActionPerformed
       RegisterUser registerUser = new RegisterUser(
                dept.getText(), 
                mat_id.getText(), 
                fullName.getText(), 
                email.getText(), 
                phone.getText(), 
                category.getSelectedItem().toString(), 
                //faculty_unit.getSelectedItem().toString(), 
                address.getText()
        
        );
        if (registerUser.validateInput()){
            try{
                registerUser.connectToDB();
                registerUser.registerUser();
                int confirmResponse = JOptionPane.showConfirmDialog(null, "SUCCESS, " + fullName.getText() + " added Successfully \n Do you wish to register another user?", "Register again?", JOptionPane.YES_NO_OPTION);
                clearInputs(); 
                // System.out.print(confirmResponse);                
                if(confirmResponse == 1){
                    new UsersPage().setVisible(true);
                    this.dispose();
                }
                
            }catch(Exception e){
                clearInputs();
                JOptionPane.showMessageDialog(null, "User already exist \n Technical errro details: " + e.toString(), "error msg", JOptionPane.ERROR_MESSAGE);
            }
        
        }

    }//GEN-LAST:event_registerUserBtnActionPerformed

    private void userLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLink_itemActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLink_itemActionPerformed

    private void resourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceLink_itemActionPerformed
        // TODO add your handling code here:
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourceLink_itemActionPerformed

    private void registerLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLinkActionPerformed

    }//GEN-LAST:event_registerLinkActionPerformed

    private void lendResourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendResourceLink_itemActionPerformed
        new LendersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendResourceLink_itemActionPerformed

    private void lendHistoryLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendHistoryLink_itemActionPerformed
        new LendersView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendHistoryLink_itemActionPerformed

    private void registeredUsersLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredUsersLink_itemActionPerformed
        new UsersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registeredUsersLink_itemActionPerformed

    private void resourcesLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesLink_itemActionPerformed
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourcesLink_itemActionPerformed

    private void logoutLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLink_itemActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLink_itemActionPerformed

   public void clearInputs(){
       dept.setText(null); 
        mat_id.setText(null); 
        fullName.setText(null); 
        email.setText(null); 
        phone.setText(null); 
        category.getSelectedItem().toString(); 
      //  faculty_unit.getSelectedItem().toString(); 
        address.setText(null);
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JTextField dept;
    private javax.swing.JMenuItem documentationlink_item;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fullName;
    private javax.swing.JMenu helpLink;
    private javax.swing.JMenu historyLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu ledersLink;
    private javax.swing.JMenuItem lendHistoryLink_item;
    private javax.swing.JMenuItem lendResourceLink_item;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem logoutLink_item;
    private javax.swing.JTextField mat_id;
    private javax.swing.JTextField phone;
    private javax.swing.JMenu registerLink;
    private javax.swing.JButton registerUserBtn;
    private javax.swing.JMenuItem registeredUsersLink_item;
    private javax.swing.JMenuItem resourceLink_item;
    private javax.swing.JMenuItem resourcesLink_item;
    private javax.swing.JMenuItem userLink_item;
    // End of variables declaration//GEN-END:variables
}
