/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_allocator;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ALLAH NA MU
 */
public class RegisterResourceView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterResourceView
     */
    public RegisterResourceView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("library_manager?characterEncoding=utf8PU").createEntityManager();
        resourcesQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT r FROM Resources r");
        resourcesList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : resourcesQuery.getResultList();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        resourceTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        resourceType = new javax.swing.JComboBox<>();
        resourceId = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        resourceCopies = new javax.swing.JSpinner();
        registerResourceBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        resourceTable = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        registerLink = new javax.swing.JMenu();
        userLink_item = new javax.swing.JMenuItem();
        resourceLink_item = new javax.swing.JMenuItem();
        ledersLink = new javax.swing.JMenu();
        lendResourceLink_item = new javax.swing.JMenuItem();
        lendHistoryLink_item = new javax.swing.JMenuItem();
        historyLink = new javax.swing.JMenu();
        registeredUsersLink_item = new javax.swing.JMenuItem();
        resourcesLink_item = new javax.swing.JMenuItem();
        helpLink = new javax.swing.JMenu();
        documentationlink_item = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        logoutLink_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 700));
        setResizable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Type:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Id:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Copies:");

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("Register/edit a resource");

        resourceType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resourceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "Magazine", "News Paper", "Journal", "Project" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Title:");

        resourceCopies.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        registerResourceBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerResourceBtn.setText("Submit");
        registerResourceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerResourceBtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Team Bob Lee (C) 2018");

        resourceTable.setAutoCreateRowSorter(true);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, resourcesList, resourceTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${type}"));
        columnBinding.setColumnName("Type");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${resourceId}"));
        columnBinding.setColumnName("Resource Id");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${title}"));
        columnBinding.setColumnName("Title");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${copies}"));
        columnBinding.setColumnName("Copies");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${availability}"));
        columnBinding.setColumnName("Availability");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(resourceTable);

        editBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editBtn.setText("EDIT");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        registerLink.setText("Register");
        registerLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLinkActionPerformed(evt);
            }
        });

        userLink_item.setText("User");
        userLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(userLink_item);

        resourceLink_item.setText("Resource");
        resourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(resourceLink_item);

        jMenuBar1.add(registerLink);

        ledersLink.setText("Lend");
        ledersLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lendResourceLink_item.setText("Lend resource");
        lendResourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendResourceLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendResourceLink_item);

        lendHistoryLink_item.setText("Lending history");
        lendHistoryLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendHistoryLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendHistoryLink_item);

        jMenuBar1.add(ledersLink);

        historyLink.setText("View");
        historyLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        registeredUsersLink_item.setText("Registered Users");
        registeredUsersLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredUsersLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(registeredUsersLink_item);

        resourcesLink_item.setText("Resources");
        resourcesLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(resourcesLink_item);

        jMenuBar1.add(historyLink);

        helpLink.setText("Help");
        helpLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        documentationlink_item.setText("About");
        helpLink.add(documentationlink_item);

        jMenuItem8.setText("Documentation");
        helpLink.add(jMenuItem8);

        jMenuBar1.add(helpLink);

        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        logoutLink_item.setText("Logout");
        logoutLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLink_itemActionPerformed(evt);
            }
        });
        logout.add(logoutLink_item);

        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resourceTitle)
                            .addComponent(resourceType, 0, 262, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resourceId)
                            .addComponent(resourceCopies, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(registerResourceBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(resourceType, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(resourceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resourceId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(resourceCopies, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addComponent(registerResourceBtn)
                .addGap(120, 120, 120)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
       
    public void clearInputs(){
                resourceId.setText(null);
                resourceTitle.setText(null);
                resourceTitle.setText(null);
        }
        
    private void registerResourceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerResourceBtnActionPerformed

        int copies = (int) resourceCopies.getValue();
        
        ResourceController resourceController = new ResourceController(
                resourceType.getSelectedItem().toString(),
                resourceId.getText(),
                resourceTitle.getText(),
                copies
        );
        
        if (resourceController.validateInput()){
            try{
                resourceController.connectToDB();
                resourceController.registerUser();
                JOptionPane.showMessageDialog(null, "SUCCESS, " + resourceTitle.getText() + " added Successfully", "Success?", JOptionPane.INFORMATION_MESSAGE);
                clearInputs();
                this.dispose();
                new RegisterResourceView().main(null);

            }catch(Exception e){
                clearInputs();
                JOptionPane.showMessageDialog(null, "Error adding resource \n Technical errro details: " + e.toString(), "error msg", JOptionPane.ERROR_MESSAGE);
            }

        }
        
    }//GEN-LAST:event_registerResourceBtnActionPerformed

    private void logoutLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLink_itemActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLink_itemActionPerformed

    private void resourcesLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesLink_itemActionPerformed
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourcesLink_itemActionPerformed

    private void registeredUsersLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredUsersLink_itemActionPerformed
        new UsersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registeredUsersLink_itemActionPerformed

    private void lendHistoryLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendHistoryLink_itemActionPerformed
        new LendersView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendHistoryLink_itemActionPerformed

    private void lendResourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendResourceLink_itemActionPerformed
        new LendersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendResourceLink_itemActionPerformed

    private void registerLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLinkActionPerformed

    }//GEN-LAST:event_registerLinkActionPerformed

    private void resourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceLink_itemActionPerformed
        // TODO add your handling code here:
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourceLink_itemActionPerformed

    private void userLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLink_itemActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLink_itemActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int selectedRowIndex = resourceTable.getSelectedRow();
        if (selectedRowIndex >= 0){
            Object resource_id = (Object) resourceTable.getModel().getValueAt(selectedRowIndex, 2);
            Object resource_title = (Object) resourceTable.getModel().getValueAt(selectedRowIndex, 3);
            Object resource_copies = (Object) resourceTable.getModel().getValueAt(selectedRowIndex, 4);
            Object resource_type = (Object) resourceTable.getModel().getValueAt(selectedRowIndex, 1);
            
            resourceId.setText(resource_id.toString());
            resourceTitle.setText(resource_title.toString());
            resourceCopies.setValue(resource_copies);
            resourceType.setSelectedItem(resource_type);

       // System.out.print(selectedRowIndex + "..........."+ resource_id + "......"+resource_title +"......."+resource_copies);
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int selectedRowIndex = resourceTable.getSelectedRow();
        
        if(selectedRowIndex >= 0 ){
            Object title = (Object) resourceTable.getModel().getValueAt(selectedRowIndex, 3);

             
             int confirmAction =  JOptionPane.showConfirmDialog(null, "Are you sure this resource is no more available?", "Confirm action", JOptionPane.YES_NO_OPTION);
             
             if(confirmAction == 0){
                try{
                   ResourceController resourceController = new ResourceController(title.toString());
                   resourceController.connectToDB();
                   resourceController.deleteResource();
                 //  JOptionPane.showMessageDialog(null, "Resource deleted..!!", "Success", JOptionPane.PLAIN_MESSAGE);
             
                   this.dispose();
                   new RegisterResourceView().main(null);
                   
                }catch(SQLException e){
                    JOptionPane.showMessageDialog(null, e, "An error has occured", JOptionPane.ERROR_MESSAGE);
                }
                
            }
            
            }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterResourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterResourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterResourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterResourceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterResourceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JMenuItem documentationlink_item;
    private javax.swing.JButton editBtn;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JMenu helpLink;
    private javax.swing.JMenu historyLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu ledersLink;
    private javax.swing.JMenuItem lendHistoryLink_item;
    private javax.swing.JMenuItem lendResourceLink_item;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem logoutLink_item;
    private javax.swing.JMenu registerLink;
    private javax.swing.JButton registerResourceBtn;
    private javax.swing.JMenuItem registeredUsersLink_item;
    private javax.swing.JSpinner resourceCopies;
    private javax.swing.JTextField resourceId;
    private javax.swing.JMenuItem resourceLink_item;
    private javax.swing.JTable resourceTable;
    private javax.swing.JTextField resourceTitle;
    private javax.swing.JComboBox<String> resourceType;
    private javax.swing.JMenuItem resourcesLink_item;
    private java.util.List<library_allocator.Resources> resourcesList;
    private javax.persistence.Query resourcesQuery;
    private javax.swing.JMenuItem userLink_item;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
