/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package library_allocator;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tasiu Kwaplong Saeed
 */
public class UsersPage extends javax.swing.JFrame {

    /**
     * Creates new form UsersPage
     */
    public UsersPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("library_manager?characterEncoding=utf8PU").createEntityManager();
        usersQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Users u");
        usersList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery.getResultList();
        usersQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Users u");
        usersList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery1.getResultList();
        usersQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT u FROM Users u");
        usersList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usersQuery2.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        dleteBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        registerLink = new javax.swing.JMenu();
        userLink_item = new javax.swing.JMenuItem();
        resourceLink_item = new javax.swing.JMenuItem();
        ledersLink = new javax.swing.JMenu();
        lendResourceLink_item = new javax.swing.JMenuItem();
        lendHistoryLink_item = new javax.swing.JMenuItem();
        historyLink = new javax.swing.JMenu();
        registeredUsersLink_item = new javax.swing.JMenuItem();
        resourcesLink_item = new javax.swing.JMenuItem();
        helpLink = new javax.swing.JMenu();
        documentationlink_item = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();
        logoutLink_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel1.setText("registered users");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Team Bob Lee (C) 2018");

        usersTable.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, usersList2, usersTable);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${category}"));
        columnBinding.setColumnName("Category");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${department}"));
        columnBinding.setColumnName("Department");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${matricOrId}"));
        columnBinding.setColumnName("Matric Or Id");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${phone}"));
        columnBinding.setColumnName("Phone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${address}"));
        columnBinding.setColumnName("Address");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);

        jScrollPane1.setViewportView(usersTable);

        dleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dleteBtn.setText("Delete Selected");
        dleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dleteBtnActionPerformed(evt);
            }
        });

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        registerLink.setText("Register");
        registerLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerLinkActionPerformed(evt);
            }
        });

        userLink_item.setText("User");
        userLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(userLink_item);

        resourceLink_item.setText("Resource");
        resourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourceLink_itemActionPerformed(evt);
            }
        });
        registerLink.add(resourceLink_item);

        jMenuBar1.add(registerLink);

        ledersLink.setText("Lend");
        ledersLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lendResourceLink_item.setText("Lend resource");
        lendResourceLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendResourceLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendResourceLink_item);

        lendHistoryLink_item.setText("Lending history");
        lendHistoryLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lendHistoryLink_itemActionPerformed(evt);
            }
        });
        ledersLink.add(lendHistoryLink_item);

        jMenuBar1.add(ledersLink);

        historyLink.setText("View");
        historyLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        registeredUsersLink_item.setText("Registered Users");
        registeredUsersLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredUsersLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(registeredUsersLink_item);

        resourcesLink_item.setText("Resources");
        resourcesLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesLink_itemActionPerformed(evt);
            }
        });
        historyLink.add(resourcesLink_item);

        jMenuBar1.add(historyLink);

        helpLink.setText("Help");
        helpLink.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        documentationlink_item.setText("About");
        helpLink.add(documentationlink_item);

        jMenuItem8.setText("Documentation");
        helpLink.add(jMenuItem8);

        jMenuBar1.add(helpLink);

        logout.setText("Logout");
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        logoutLink_item.setText("Logout");
        logoutLink_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLink_itemActionPerformed(evt);
            }
        });
        logout.add(logoutLink_item);

        jMenuBar1.add(logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(dleteBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(217, 217, 217))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145)
                .addComponent(dleteBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(31, 31, 31))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = usersTable.getSelectedRow();
        Object matric_id = (Object) usersTable.getModel().getValueAt(selectedRowIndex, 3);
       
        
        RegisterUser deleteUser = new RegisterUser(matric_id);

            try{

               int confirmResponse = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete user?", "Confirm action", JOptionPane.YES_NO_OPTION);
                            
                if(confirmResponse == 0){
                    deleteUser.connectToDB();
                    deleteUser.deleteUser();
                    this.dispose();
                    new UsersPage().main(null);
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Sorry, User cannot be deleted \n Technical details:" + e.toString(), "Error msg", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_dleteBtnActionPerformed

    private void userLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLink_itemActionPerformed
        new MainPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_userLink_itemActionPerformed

    private void resourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourceLink_itemActionPerformed
        // TODO add your handling code here:
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourceLink_itemActionPerformed

    private void registerLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLinkActionPerformed

    }//GEN-LAST:event_registerLinkActionPerformed

    private void lendResourceLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendResourceLink_itemActionPerformed
        new LendersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendResourceLink_itemActionPerformed

    private void lendHistoryLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lendHistoryLink_itemActionPerformed
        new LendersView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lendHistoryLink_itemActionPerformed

    private void registeredUsersLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredUsersLink_itemActionPerformed
        new UsersPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registeredUsersLink_itemActionPerformed

    private void resourcesLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesLink_itemActionPerformed
        new RegisterResourceView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_resourcesLink_itemActionPerformed

    private void logoutLink_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLink_itemActionPerformed
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutLink_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsersPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsersPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dleteBtn;
    private javax.swing.JMenuItem documentationlink_item;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JMenu helpLink;
    private javax.swing.JMenu historyLink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu ledersLink;
    private javax.swing.JMenuItem lendHistoryLink_item;
    private javax.swing.JMenuItem lendResourceLink_item;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem logoutLink_item;
    private javax.swing.JMenu registerLink;
    private javax.swing.JMenuItem registeredUsersLink_item;
    private javax.swing.JMenuItem resourceLink_item;
    private javax.swing.JMenuItem resourcesLink_item;
    private javax.swing.JMenuItem userLink_item;
    private java.util.List<library_allocator.Users> usersList;
    private java.util.List<library_allocator.Users> usersList1;
    private java.util.List<library_allocator.Users> usersList2;
    private javax.persistence.Query usersQuery;
    private javax.persistence.Query usersQuery1;
    private javax.persistence.Query usersQuery2;
    private javax.swing.JTable usersTable;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
